# Exported Floating-KinDyn-Graph manipulator model parameters.

float64[4] link_masses
float64[12] link_first_moments
float64[24] link_inertias
float64[4] viscous_friction
float64[4] coulomb_friction
float64[4] static_friction
float64[4] stribeck_velocity
float64[3] gravity_vector
float64[3] payload_com
float64 payload_mass
float64[3] payload_inertia
float64[6] base_pose
float64[6] world_pose
float64[6] tip_offset_pose

float64 joint_lock_on_deadband
float64 joint_lock_off_deadband
float64 baumgarte_alpha
float64 endeffector_mass
float64 endeffector_damping
float64 endeffector_stiffness
