controller_manager:
  ros__parameters:
    update_rate: 25  #Hz
    is_async: True

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# get vehicle base to manipulator base TF
# ros2 run tf2_ros tf2_echo base_link alpha_base_link 

# joint_state_broadcaster:
#   ros__parameters:
#     map_interface_to_joint_state:
#       effort: effort
#       position: position
#       velocity: velocity
#       acceleration: acceleration
#       current: current
#       stateId: stateId
