// Auto-generated by tools/generate_manifest_and_registry.py
// Author: edward morgan
#include "casadi_on_gpu_kernel_registry.h"
#include "Mnext_reg_fe5.cuh"
#include "Vnext_reg.cuh"
#include <stdexcept>
#include <string>

namespace casadi_on_gpu {
namespace {
CUDA_GLOBAL void dispatch_Vnext_reg_kernel(const casadi_real* i0_in, const casadi_real* i1_in, const casadi_real* i2_in, const casadi_real* i3_in, const casadi_real* i4_in, casadi_real* o0_out, int n_candidates) {
  int idx = blockIdx.x * blockDim.x + threadIdx.x;
  if (idx >= n_candidates) return;
  const casadi_real* i0 = i0_in + 12 * idx;
  const casadi_real* i1 = i1_in + 6 * idx;
  const casadi_real* i2 = i2_in + 33 * idx;
  const casadi_real* i3 = i3_in + 1 * idx;
  const casadi_real* i4 = i4_in + 6 * idx;
  casadi_real* o0 = o0_out + 12 * idx;
  const casadi_real* arg_local[5] = {0};
  casadi_real* res_local[1] = {0};
  arg_local[0] = i0;
  arg_local[1] = i1;
  arg_local[2] = i2;
  arg_local[3] = i3;
  arg_local[4] = i4;
  res_local[0] = o0;
  casadi_int iw[1];
  casadi_real w[830];
  Vnext_reg(arg_local, res_local, iw, w, 0);
}

void launch_Vnext_reg(const std::uintptr_t* input_ptrs, const std::uintptr_t* output_ptrs, int blocks, int threads_per_block, cudaStream_t stream, int n_candidates) {
  auto* i0 = reinterpret_cast<const casadi_real*>(input_ptrs[0]);
  auto* i1 = reinterpret_cast<const casadi_real*>(input_ptrs[1]);
  auto* i2 = reinterpret_cast<const casadi_real*>(input_ptrs[2]);
  auto* i3 = reinterpret_cast<const casadi_real*>(input_ptrs[3]);
  auto* i4 = reinterpret_cast<const casadi_real*>(input_ptrs[4]);
  auto* o0 = reinterpret_cast<casadi_real*>(output_ptrs[0]);
  dispatch_Vnext_reg_kernel<<<blocks, threads_per_block, 0, stream>>>(i0, i1, i2, i3, i4, o0, n_candidates);
}

CUDA_GLOBAL void dispatch_Mnext_reg_kernel(const casadi_real* i0_in, const casadi_real* i1_in, const casadi_real* i2_in, const casadi_real* i3_in, const casadi_real* i4_in, const casadi_real* i5_in, const casadi_real* i6_in, const casadi_real* i7_in, const casadi_real* i8_in, casadi_real* o0_out, int n_candidates) {
  int idx = blockIdx.x * blockDim.x + threadIdx.x;
  if (idx >= n_candidates) return;
  const casadi_real* i0 = i0_in + 10 * idx;
  const casadi_real* i1 = i1_in + 5 * idx;
  const casadi_real* i2 = i2_in + 1 * idx;
  const casadi_real* i3 = i3_in + 81 * idx;
  const casadi_real* i4 = i4_in + 1 * idx;
  const casadi_real* i5 = i5_in + 1 * idx;
  const casadi_real* i6 = i6_in + 1 * idx;
  const casadi_real* i7 = i7_in + 4 * idx;
  const casadi_real* i8 = i8_in + 1 * idx;
  casadi_real* o0 = o0_out + 10 * idx;
  const casadi_real* arg_local[9] = {0};
  casadi_real* res_local[1] = {0};
  arg_local[0] = i0;
  arg_local[1] = i1;
  arg_local[2] = i2;
  arg_local[3] = i3;
  arg_local[4] = i4;
  arg_local[5] = i5;
  arg_local[6] = i6;
  arg_local[7] = i7;
  arg_local[8] = i8;
  res_local[0] = o0;
  casadi_int iw[1];
  casadi_real w[1073];
  Mnext_reg(arg_local, res_local, iw, w, 0);
}

void launch_Mnext_reg(const std::uintptr_t* input_ptrs, const std::uintptr_t* output_ptrs, int blocks, int threads_per_block, cudaStream_t stream, int n_candidates) {
  auto* i0 = reinterpret_cast<const casadi_real*>(input_ptrs[0]);
  auto* i1 = reinterpret_cast<const casadi_real*>(input_ptrs[1]);
  auto* i2 = reinterpret_cast<const casadi_real*>(input_ptrs[2]);
  auto* i3 = reinterpret_cast<const casadi_real*>(input_ptrs[3]);
  auto* i4 = reinterpret_cast<const casadi_real*>(input_ptrs[4]);
  auto* i5 = reinterpret_cast<const casadi_real*>(input_ptrs[5]);
  auto* i6 = reinterpret_cast<const casadi_real*>(input_ptrs[6]);
  auto* i7 = reinterpret_cast<const casadi_real*>(input_ptrs[7]);
  auto* i8 = reinterpret_cast<const casadi_real*>(input_ptrs[8]);
  auto* o0 = reinterpret_cast<casadi_real*>(output_ptrs[0]);
  dispatch_Mnext_reg_kernel<<<blocks, threads_per_block, 0, stream>>>(i0, i1, i2, i3, i4, i5, i6, i7, i8, o0, n_candidates);
}

const KernelEntry kRegistry[] = {
  {"Vnext_reg", "Vnext_reg_kernel", 5, 1, 5, 1, 0, 830, {0, 1, 2, 3, 4}, {12, 6, 33, 1, 6}, {12}, launch_Vnext_reg},
  {"Mnext_reg", "Mnext_reg_kernel", 9, 1, 9, 1, 0, 1073, {0, 1, 2, 3, 4, 5, 6, 7, 8}, {10, 5, 1, 81, 1, 1, 1, 4, 1}, {10}, launch_Mnext_reg},
};

}  // namespace

const KernelEntry* get_kernel_registry(std::size_t* count) {
  *count = sizeof(kRegistry) / sizeof(kRegistry[0]);
  return kRegistry;
}

}  // namespace casadi_on_gpu
