bool reset_manipulator
bool reset_vehicle
bool hold_commands

bool use_manipulator_state
float64[5] manipulator_position
float64[5] manipulator_velocity

bool use_vehicle_state
# Vehicle pose is [x, y, z, roll, pitch, yaw].
float64[6] vehicle_pose
# Vehicle twist is [u, v, w, p, q, r].
float64[6] vehicle_twist
# Vehicle wrench is [Fx, Fy, Fz, Tx, Ty, Tz].
float64[6] vehicle_wrench

bool use_coupled_dynamics
bool set_vehicle_dynamics
SimVehicleDynamics vehicle_dynamics
bool set_manipulator_dynamics
SimManipulatorDynamics manipulator_dynamics
---
bool success
string message
